Library/Library/Controllers/AdminController.cs
using DataAccess.Entity;
using DataAccess.Repository;
using Library.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class AdminController : Controller
    {
        private UserRepository repo;
        public AdminController()
        {
            repo = new UserRepository();
        }

        public ActionResult Index()
        {
            if (AuthenticationManager.LoggedUser != null && AuthenticationManager.IsAdmin() == true)
            {
                List<User> users;
                users = repo.GetAll();
                User admin = repo.GetAll().Where(u => u.IsAdmin = true).FirstOrDefault();
                users.Remove(admin);
                return View(users);
            }
            return RedirectToAction("Login", "Home");
        }

        public ActionResult Edit(int id)
        {
            if (AuthenticationManager.LoggedUser != null && AuthenticationManager.IsAdmin() == true)
            {
                User user = repo.GetById(id);
                if (user == null)
                {
                    return RedirectToAction("Index");
                }

                return View(user);

            }
            return RedirectToAction("Login", "Home");
        }
        [HttpPost]
        public ActionResult Edit(User model)
        {
            if (AuthenticationManager.LoggedUser != null && AuthenticationManager.IsAdmin() == true)
            {
                User user = repo.GetById(model.Id);
                user.IsAdmin = model.IsAdmin;
                repo.Save(user);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Login", "Home");
        }

        public ActionResult Delete(int id)
        {
            if (AuthenticationManager.LoggedUser != null && AuthenticationManager.IsAdmin() == true)
            {
                User user = repo.GetById(id);
                repo.Delete(user);
                return RedirectToAction("Index");

            }
            return RedirectToAction("Login", "Home");
        }

    }
}

Library/Library/Controllers/UserBooksController.cs
using DataAccess.Entity;
using DataAccess.Repository;
using Library.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Library.Controllers
{
    public class UserBooksController : Controller
    {
        protected ApplicationDbContext context;
        protected BookRepository bookRepo;
        public UserBooksController()
        {
            context = new ApplicationDbContext();
            bookRepo = new BookRepository();
        }

        public ActionResult Index(int? bookId)
        {
            if (AuthenticationManager.LoggedUser == null)
                return RedirectToAction("Login", "Home");

            User user = context.Users.Where(u => u.Id == AuthenticationManager.LoggedUser.Id).FirstOrDefault();
            if (bookId == null)
                return View(user.BooksRead);

            Book book = context.Books.Where(b => b.Id == bookId.Value).FirstOrDefault();
            if (book == null)
            {
                return RedirectToAction("Index","Books");
            }

            if (book.UsersMarkedAsRead.Where(u => u.Id == AuthenticationManager.LoggedUser.Id).FirstOrDefault() == null)
            {
                user.BooksRead.Add(book);
                book.UsersMarkedAsRead.Add(user);
                book.TimesRead++;
                context.SaveChanges();
            }
            else
            {
                user.BooksRead.Remove(book);
                book.UsersMarkedAsRead.Remove(user);
                book.TimesRead--;
                context.SaveChanges();
            }

            return View(user.BooksRead);
        }
    }
}

Library/Library/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Book Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Books", "Index", "Books")</li>
                    @if (Library.Models.AuthenticationManager.LoggedUser != null&& Library.Models.AuthenticationManager.IsAdmin())
                    {
                        <li>@Html.ActionLink("Genres", "Index", "Genres")</li>

                    }
                    <li>@Html.ActionLink("Authors", "Index", "Authors")</li>
                    @if (Library.Models.AuthenticationManager.LoggedUser != null)
                    {
                        if (Library.Models.AuthenticationManager.IsAdmin())
                        {
                            <li>@Html.ActionLink("Users", "Index", "Admin")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("My Books", "Index", "UserBooks")</li>

                        }

                    }
                </ul>
                @if (Library.Models.AuthenticationManager.LoggedUser != null)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Logout", "Logout", "Home", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Register", "Register", "Home", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                        <li>@Html.ActionLink("Log in", "Login", "Home", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                    </ul>

                }
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Book Store Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>